CREATE TABLE R (A INT, B INT, C INT, D INT, E INT, F INT);

CREATE TABLE F (x VARCHAR(10), y VARCHAR(10), violation BOOLEAN, motivation VARCHAR(200));

CREATE TABLE R1 (E INT, D INT); --E>D
CREATE TABLE F1 (x VARCHAR(10), y VARCHAR(10), violation BOOLEAN, motivation VARCHAR(200));

CREATE TABLE R2 (A INT, B INT, C INT, E INT, F INT); --ABC > EF, E > A
CREATE TABLE F2 (x VARCHAR(10), y VARCHAR(10), violation BOOLEAN, motivation VARCHAR(200));

CREATE TABLE R2a (E INT, A INT); --E>A
CREATE TABLE F2a (x VARCHAR(10), y VARCHAR(10), violation BOOLEAN, motivation VARCHAR(200));

CREATE TABLE R2b (B INT, C INT, E INT, F INT); -- EBC > F
CREATE TABLE F2b (x VARCHAR(10), y VARCHAR(10), violation BOOLEAN, motivation VARCHAR(200));
